package rules
 
import com.javainuse.model.Product
import com.javainuse.model.HCP

dialect  "mvel"

rule "Offer for Diamond"
	when 
		productObject: Product(type=="diamond")
	then
		productObject.setDiscount(15);
	end
rule "Offer for Gold"
	when 
		productObject: Product(type=="gold")
	then
		productObject.setDiscount(25);
	end
rule "Dilip -- test"
	when
		productObject: Product(type=="HCP") 
	then
		productObject.setDiscount(15);
	end
	
rule "Route HCPs in US"
	when 
		hcpObj: HCP(country=="US")
	then
		hcpObj.setRouteTo("Aligarh");
	end
	
rule "Route HCPs with Name"		
	when 
		hcpObj: HCP(name=="Tuglar")
	then
		hcpObj.setRouteTo("Nazareth");
	end
rule "Route HCPs with Name2"	
	when 
		hcpObj: HCP(name=="Salty")
	then
		hcpObj.setRouteTo("Georgetown");
	end
	
rule "Route for Address"
	when 
		hcp: HCP(address=="Nazareth")
	then
		hcp.setRouteTo("Sudan")
	end
rule "Route for Address2"
	when 
		hcp: HCP(address!="Nazareth")
	then
		hcp.setRouteTo("Mumbai-Delhi")
	end
	